# fly.toml app configuration file generated for purple-forest-3678 on 2023-06-28T12:35:18-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "purple-forest-3678"
primary_region = "atl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
